import type { ScenarioDocument } from "./types";

export const DEFAULT_SCENARIO: ScenarioDocument = {
  courseInfo: {
    courseTitle: "",
    department: "",
    scenarioTitle: "",
    targetLearnerGroup: "",
    numberOfTrainees: "",
    numberOfInstructors: "",
    levelOfExperience: "",
    prerequisiteKnowledge: "",
  },
  objectives: ["", "", "", ""],
  clinicalSetting: {
    settingRequired: "",
    remarks: "",
  },
  instructors: [""],
  confederates: [""],
  traineeRoles: [""],
  patientInfo: {
    name: "",
    showOnMonitorBeforeStart: false,
    makeAvailableDuringSimulation: false,
    identificationNo: "",
    race: "",
    age: "",
    gender: "",
    weight: "",
    height: "",
    pastMedicalAndSocialHistory: "",
    currentMedications: "",
    foodDrugAllergies: "",
    primaryCareProvider: "",
    presentingComplaintHistory: "",
  },
  scenarioInfo: {
    timeAllocatedForScenario: "",
    timeAllocatedForDebrief: "",
    scenarioSummary: "",
    scenarioInformationToTrainees: "",
    transitionMode: "next",
  },
  scenarioFlow: [
    {
      stateName: "",
      vitalSigns: {
        bp: "",
        pr: "",
        rr: "",
        spo2: "",
        rhythm: "",
      },
      physicalExamDisplayedOnSimMan: [""],
      physicalExamVolunteeredByInstructor: [""],
      investigations: [""],
      expectedActions: [""],
      remarks: [""],
      instructorControl: [""],
      transitionRule: "next",
    },
  ],
  equipment: [
    {
      category: "Airway and breathing",
      item: "",
      quantity: "",
      remarks: "",
    },
  ],
  debriefInfo: {
    numberOfDebriefers: "",
    debriefRoomSetup: "",
    debriefDescription: "",
    logisticsRequired: "",
  },
  simulatorPrep: [""],
  monitorSetup: {
    layout: ["5 waveform"],
    parameters: ["Primary Electrocardiogram", "SPO2 (Plethysmogram)", "NBP- Non-invasive Blood Pressure", "HR- Heart Rate", "Pulse"],
  },
  appendixImages: [],
  documentInfo: {
    author: "",
    designation: "",
    department: "",
    dateScenarioDeveloped: "",
    dateScenarioUpdated: "",
  },
};
