export const ALLOWED_MONITOR_LAYOUTS = [
  "5 waveform",
  "4 waveform",
  "3 waveform",
  "Big Num layout",
] as const;

export const ALLOWED_MONITOR_PARAMETERS = [
  "Primary Electrocardiogram",
  "Secondary Electrocardiogram",
  "ABP - Arterial Blood Pressure",
  "SPO2 (Plethysmogram)",
  "PAP - Pulmonary Artery Pressure",
  "CO2 – End-tidal Carbon Dioxide",
  "pH – Aterial pH",
  "CVP - Central Venous Pressure",
  "NBP- Non-invasive Blood Pressure",
  "TOF - Train Of Four",
  "N2O - Nitrous Oxide",
  "O2 - Oxygen pressure",
  "Pulse",
  "WP – Wedge Pattern",
  "RR - Airway Respiration Rate",
  "C.O. - Cardiac Output",
  "TPeri - Peripheral Temperature",
  "Tblood - Invasive blood temperature",
  "ICP - Intracranial pressure",
  "AGT – Agent",
  "HR- Heart Rate",
] as const;

export const ALLOWED_HEART_SOUNDS = [
  "Aortic Stenosis",
  "Austin Flint Murmur",
  "Friction Rub",
  "Mitral Valve Prolapse",
  "Systolic Murmur",
  "Diastolic Murmur",
  "OS70",
  "Stills Murmur",
  "Ventricular Septal Defect",
  "Atrial Septal Defect",
  "Pulmonary Stenosis",
  "Holosystolic Murmur",
  "Early Systolic Murmur",
  "Gallop",
  "Continuous Murmur",
] as const;

export const ALLOWED_LUNG_SOUNDS = [
  "Crackles",
  "Gurgling Rhonchi",
  "Pleura Rub",
  "Pneumonia",
  "Rhonchi",
  "Stridor",
  "Wheezes",
  "Crepitations",
  "Absent breath sounds",
] as const;

export const ALLOWED_BOWEL_SOUNDS = [
  "Normal Bowel 20 years old",
  "Normal Bowel 60 years old",
  "Borborygmus",
  "Crohns Disease",
  "Diarrhea",
  "Hyperactive",
  "Hyperactive Bowel 16 Years old",
  "Hypoactive",
  "Hypoactive Bowel Codeine",
  "Hypoactive Bowel Postop",
  "Hypoactive Bowel Preop",
  "Irritable Bowel Syndrome",
  "Ulcerative Colitis",
  "Hypoactive 50sec",
] as const;

export const ALLOWED_SIMMAN_CAPABILITIES = [
  "Spontaneous breathing",
  "Bilateral chest rise and fall",
  "Unilateral chest rise and fall",
  "Foreign body airway obstruction",
  "Tongue edema",
  "Pharyngeal swelling",
  "Laryngospasm",
  "Decreased cervical range of motion",
  "Trismus",
  "Can’t intubate / can ventilate",
  "Can’t intubate / can’t ventilate",
  "Head tilt/Chin lift",
  "Jaw thrust",
  "Suctioning",
  "Bag-mask ventilation",
  "Intubation",
  "Cricoid pressure",
  "Laryngeal mask airway insertion",
  "Chest Tube Insertion",
  "Needle decompression for tension pneumothorax",
  "Transcutaneous pacing",
  "Defibrillation",
  "Cardioversion",
  "Cardiopulmonary resuscitation",
  "Palpation of pulses",
  "Secretions",
  "Sweat",
  "Tears",
  "Froth",
  "Urine",
  "Convulsions",
  "Bleeding (venous/arterial)",
  "Difficulty breathing",
  "Vomiting",
  "Cough",
  "Moaning",
  "IV Access (Right Arm Only)",
  "Intra-osseous access (sternum, tibial)",
] as const;

export const SOUND_LABELS = [
  "Heart Sound",
  "Lung Sound",
  "Bowel Sound",
] as const;

export const MONITOR_LIMITS = {
  maxWaveforms: 5,
  maxNumericParameters: 14,
};
